parameters:
  - name: sonar
    displayName: Sonar enabled
    type: boolean
    default: false

  - name: aquascan
    displayName: Aquascan enabled
    type: boolean
    default: false

trigger:
- main

pool:
#  vmImage: ubuntu-latest
  name: Default

stages:
  - stage: Build
    displayName: Build Docker Image
    jobs:
      - template: azure-pipelines-build.yml
